{"uuid": "62d427b6-c4ca-4130-85ec-e97bfc53d0c9", "children": ["e654df3f-958e-4c0c-a9b3-8bb3383a4f2f"], "befores": [{"name": "get_test_user_token_fixture", "status": "broken", "statusDetails": {"message": "KeyError: 'data'\n", "trace": "  File \"C:\\Users\\changan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\changan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\changan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\changan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\changan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\changan\\Documents\\python\\RbacTest\\testcases\\conftest.py\", line 67, in get_test_user_token_fixture\n    return loginInfo.data['data']['token']\n"}, "steps": [{"name": "前置步骤 ==>> 获取测试用户token", "status": "passed", "start": 1730794803921, "stop": 1730794803921}], "start": 1730794803921, "stop": 1730794804349}], "start": 1730794803921, "stop": 1730794804411}