INFO     log:test_05_updatePassword.py:18 *************** 开始执行用例 ***************
INFO     log:http_client.py:40 接口请求地址 ==>> http://127.0.0.1/index/getRsaEncodePassword
INFO     log:http_client.py:41 接口请求方式 ==>> POST
INFO     log:http_client.py:43 接口请求头 ==>> {
    "Content-Type": "application/x-www-form-urlencoded"
}
INFO     log:http_client.py:47 接口请求体 data 参数 ==>> {
    "password": "18592037348"
}
INFO     log:index_user_api.py:15 接口实际返回的结果为==>>{
    "success": true,
    "code": 200,
    "message": "操作成功",
    "time": "1730794612937",
    "data": "jP2kDqowq2OA17KjIG1gpKMIZXFVSAgjTa46vPldtsoUuJXH5R9XxHNLU1Rt8kTzqR5mIudnR7uva9qzl7@IiVYHewf7Pj5QX3ixhWMfOzWyNb1l9u5KYsbZYafeK0QNekCiaZiS1@L/rsHre80tPCnkjwnMwTADPelEwCTBWgY=",
    "path": null,
    "timestamp": null,
    "msg": null,
    "trackId": null
}
INFO     log:http_client.py:40 接口请求地址 ==>> http://127.0.0.1/index/getRsaEncodePassword
INFO     log:http_client.py:41 接口请求方式 ==>> POST
INFO     log:http_client.py:43 接口请求头 ==>> {
    "Content-Type": "application/x-www-form-urlencoded"
}
INFO     log:http_client.py:47 接口请求体 data 参数 ==>> {
    "password": "18592037348"
}
INFO     log:index_user_api.py:15 接口实际返回的结果为==>>{
    "success": true,
    "code": 200,
    "message": "操作成功",
    "time": "1730794613059",
    "data": "WLBrNNWmvBCtpWSMQ34fPBfoH3AHmZXkh2GbrYD4x/GvJnOva60zBtmN0WZs2fgL@6Iai9Zwojg2BR7OGTbThdgyUNjcsSplwLWsk2IWIZXJEgmisC2Mvk2Ch5SP17ovOWJwldr2Z@hKLi3m9Imve1IbCMfhGp1WC6qDpGCfCbk=",
    "path": null,
    "timestamp": null,
    "msg": null,
    "trackId": null
}
INFO     log:http_client.py:40 接口请求地址 ==>> http://127.0.0.1/user/updatePassword
INFO     log:http_client.py:41 接口请求方式 ==>> POST
INFO     log:http_client.py:43 接口请求头 ==>> {
    "Content-Type": "application/x-www-form-urlencoded",
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyYmFjLXVzZXIiLCJpc3MiOiJsb25nY2hhbyIsImlhdCI6MTczMDc5NDYwOCwiZXhwIjoxNzMwNzk4MjA4LCJpZCI6MTg0NjgwMTQ0MjQzMzY4MzQ1OH0.HD2tnYBoq20ZqRQIIc1N2W2SnGUeqmvBhOeGj3Ic54E"
}
INFO     log:http_client.py:47 接口请求体 data 参数 ==>> {
    "userId": 1846801442433683458,
    "oldPassword": "jP2kDqowq2OA17KjIG1gpKMIZXFVSAgjTa46vPldtsoUuJXH5R9XxHNLU1Rt8kTzqR5mIudnR7uva9qzl7@IiVYHewf7Pj5QX3ixhWMfOzWyNb1l9u5KYsbZYafeK0QNekCiaZiS1@L/rsHre80tPCnkjwnMwTADPelEwCTBWgY=",
    "newPassword": "WLBrNNWmvBCtpWSMQ34fPBfoH3AHmZXkh2GbrYD4x/GvJnOva60zBtmN0WZs2fgL@6Iai9Zwojg2BR7OGTbThdgyUNjcsSplwLWsk2IWIZXJEgmisC2Mvk2Ch5SP17ovOWJwldr2Z@hKLi3m9Imve1IbCMfhGp1WC6qDpGCfCbk="
}
INFO     log:index_user_api.py:15 接口实际返回的结果为==>>{
    "success": false,
    "code": 9992,
    "message": "你没有权限访问该接口！",
    "time": 1730794613575,
    "path": null,
    "timestamp": null,
    "msg": null,
    "trackId": null
}
INFO     log:conftest.py:29 code ==>> 期望结果：9992， 实际结果：9992
INFO     log:conftest.py:30 返回信息 ==>> 期望结果：你没有权限访问该接口！， 实际结果：你没有权限访问该接口！
INFO     log:test_05_updatePassword.py:27 *************** 结束执行用例 ***************