{"uuid": "d9c9d4a1-c3a1-49df-8617-88ff588d8efd", "children": ["a7ae5316-e2cf-4f73-a752-0ef14dc09cd3"], "befores": [{"name": "get_test_user_token_fixture", "status": "broken", "statusDetails": {"message": "KeyError: 'data'\n", "trace": "  File \"C:\\Users\\changan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\changan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\changan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\changan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\changan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\changan\\Documents\\python\\RbacTest\\testcases\\conftest.py\", line 67, in get_test_user_token_fixture\n    return loginInfo.data['data']['token']\n"}, "steps": [{"name": "前置步骤 ==>> 获取测试用户token", "status": "passed", "start": 1730794784698, "stop": 1730794784699}], "start": 1730794784698, "stop": 1730794785527}], "start": 1730794784698, "stop": 1730794785588}