{"name": "test_logout_reverse[18592037348-test-False-10007-当前用户不存在！]", "status": "failed", "statusDetails": {"message": "AssertionError: 接口返回码是 【 200 】, 返回信息：操作成功 \nassert True == False\n +  where True = <service.result_base.ResultBase object at 0x000001DCC53A7F10>.success", "trace": "self = <testcases.api_test.index_uesr_test.test_03_logout.TestLogout object at 0x000001DCC5231D00>, userId = 18592037348, token = 'test', expect_result = False, expect_code = 10007, expect_msg = '当前用户不存在！'\n\n    @allure.story(\"用例--用户登出--逆向\")\n    @allure.description(\"该用例是针对用户登出接口的测试\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"userId,token, expect_result, expect_code, expect_msg\",\n                             api_data[\"test_logout_reverse\"])\n    def test_logout_reverse(self, userId, token, expect_result, expect_code, expect_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = logout(uesrId=userId, token=token)\n>       assert_results(result, expect_result, expect_code, expect_msg)\n\ntest_03_logout.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresult = <service.result_base.ResultBase object at 0x000001DCC53A7F10>, expect_result = False, expect_code = 10007, expect_msg = '当前用户不存在！'\n\n    def assert_results(result, expect_result, expect_code, expect_msg):\n        \"\"\"\n        断言结果并记录日志。\n        参数:\n            result: 实际结果对象，应该包含success, error, data等属性。\n            expect_result: 期望的成功状态。\n            expect_code: 期望的返回code。\n            expect_msg: 期望的返回message。\n        \"\"\"\n    \n        # 断言实际结果与期望结果相同\n>       assert result.success == expect_result, result.error\nE       AssertionError: 接口返回码是 【 200 】, 返回信息：操作成功 \nE       assert True == False\nE        +  where True = <service.result_base.ResultBase object at 0x000001DCC53A7F10>.success\n\n..\\..\\conftest.py:24: AssertionError"}, "description": "该用例是针对用户登出接口的测试", "attachments": [{"name": "log", "source": "e97afa04-13b5-4621-b2b3-8ca6438f7cf1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "userId", "value": "18592037348"}, {"name": "token", "value": "'test'"}, {"name": "expect_result", "value": "False"}, {"name": "expect_code", "value": "10007"}, {"name": "expect_msg", "value": "'当前用户不存在！'"}], "start": 1729670198977, "stop": 1729670199393, "uuid": "7ad46f73-3e10-4e05-a53c-cedda2a2a3a5", "historyId": "464b5419ba8583f0b04270e7922c73b0", "testCaseId": "884b2de7e611bef83da2e33a6dd06fc8", "fullName": "testcases.api_test.index_uesr_test.test_03_logout.TestLogout#test_logout_reverse", "labels": [{"name": "story", "value": "用例--用户登出--逆向"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "feature", "value": "用户公共基础模块"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test.index_uesr_test"}, {"name": "suite", "value": "test_03_logout"}, {"name": "subSuite", "value": "TestLogout"}, {"name": "host", "value": "CQCA202413058N"}, {"name": "thread", "value": "21540-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.index_uesr_test.test_03_logout"}]}